### PR TITLE
PHP 8.2 warning fixes

### PR DESCRIPTION
**Pull request by websmurf**
This fixes the php 8.0 deprecation warning in the code (as mentioned in #53)

### CODE REVIEW

**Comment by Millon15** [comment]
@websmurf Howdy! Fortunatelly this PR issue has been fixed in previous PRs, that has been already merged to the `master` branch of this repo by maintainer:

- https://github.com/MenaraSolutions/geographer/pull/48
- https://github.com/MenaraSolutions/geographer/pull/49

So, scince last **Release** in this repo has been created 2 yers ago, to fix the issue in your project, that depends from this (`MenaraSolutions/geographer`) package, you need to:

1. Modify your `composer.json`

```json
{
    "name": "you/your-awsome-project",
    "require": {
        "menarasolutions/geographer": "dev-master"
    }
}
```

2. Fire: `composer update menarasolutions/geographer`

**Comment by websmurf** [comment]
Hi @Millon15 

My title was incorrect. These are the errors we get on php 8.2:

```
Return type of MenaraSolutions\Geographer\Divisible::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
Warning: Uncaught Error: Object of class UnwindExit could not be converted to string in /var/www/vendor/menarasolutions/geographer/src/Divisible.php:17 Stack trace: #0 /var/www/vendor/composer/ClassLoader.php(576): include() 
#1 /var/www/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/var/www/vendor...') 
#2 /var/www/vendor/menarasolutions/geographer/src/Earth.php(8): Composer\Autoload\ClassLoader->loadClass('MenaraSolutions...') 
#3 /var/www/vendor/composer/ClassLoader.php(576): include('/var/www/vendor...') 
#4 /var/www/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/var/www/vendor...') 
... snip ...
#15 {main} thrown in /var/www/vendor/menarasolutions/geographer/src/Divisible.php on line 17

Fatal error: During inheritance of ArrayAccess: Uncaught in /var/www/vendor/menarasolutions/geographer/src/Divisible.php on line 17
```

The annotation added here will avoid this

**Comment by Millon15** [comment]
@websmurf Yeah I got that! Abovementioned PRs has been already merged to the `master` of this repo and ALREADY fixed that `Warning`.
I tested it on my PROD - believe me :)
So this PR of yours can be safely closed. Just sayin'

**Comment by websmurf** [comment]
Ah, I see. But there was no release for those changes yet right?

**Comment by Millon15** [comment]
Yeah, as I mentioned in my very first comment: "So, scince last Release in this repo has been created 2 yers ago" :)

**Comment by websmurf** [comment]
confirmed!

**Pull request closed without merging**
